steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nyaya-sahayak:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nyaya-sahayak:latest'
      - '-f'
      - 'project/Dockerfile'
      - 'project'
    timeout: 1200s

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nyaya-sahayak:$COMMIT_SHA'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nyaya-sahayak:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nyaya-sahayak-core'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nyaya-sahayak:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/nyaya-sahayak:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nyaya-sahayak:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
