import React, { useRef } from 'react';
import { Download, FileCheck, AlertTriangle, CheckCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown'; // Ensure we install this later if needed, or just use dangerous HTML

const ResultsPanel = ({ noticeContent, onReset }) => {
    const contentRef = useRef(null);

    const handlePrint = () => {
        // Basic print logic - in real app, might fetch a PDF from backend
        const printContent = contentRef.current.innerHTML;
        const originalContent = document.body.innerHTML;
        document.body.innerHTML = printContent;
        window.print();
        document.body.innerHTML = originalContent;
        window.location.reload(); // Quick fix to restore state after print
    };

    return (
        <div className="glass-panel p-8 w-full animate-fade-in-up">
            <div className="flex flex-col md:flex-row gap-8">

                {/* Left: Score Gauge (Static Mockup for Phase 2) */}
                <div className="md:w-1/3 flex flex-col items-center justify-center p-6 bg-white/5 rounded-xl border border-white/10">
                    <h3 className="text-xl font-bold text-amber-500 mb-4">AI CONFIDENCE</h3>
                    <div className="relative w-40 h-40 flex items-center justify-center rounded-full border-8 border-gray-700">
                        <div className="absolute w-full h-full rounded-full border-8 border-amber-500 border-t-transparent animate-spin-slow" style={{ transform: 'rotate(45deg)' }}></div>
                        <div className="text-3xl font-bold text-white">87%</div>
                    </div>
                    <p className="text-sm text-gray-400 mt-4 text-center">High probability of successful resolution based on provided facts.</p>
                </div>

                {/* Right: Document */}
                <div className="md:w-2/3">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="text-xl font-bold text-white flex items-center">
                            <FileCheck className="mr-2 text-green-400" /> GENERATED NOTICE
                        </h3>
                        <div className="space-x-2">
                            <button onClick={handlePrint} className="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded text-sm flex items-center">
                                <Download size={16} className="mr-2" /> Download PDF
                            </button>
                            <button onClick={onReset} className="px-4 py-2 bg-amber-600 hover:bg-amber-500 rounded text-sm text-white">
                                New Case
                            </button>
                        </div>
                    </div>

                    <div className="bg-white text-black p-8 rounded-lg shadow-xl font-serif text-sm leading-relaxed max-h-[500px] overflow-y-auto" ref={contentRef}>
                        {/* Notice Content Rendering */}
                        <div dangerouslySetInnerHTML={{ __html: noticeContent.replace(/\n/g, '<br/>') }} />

                        <div className="mt-8 pt-8 border-t border-gray-300">
                            <p><strong>Yours faithfully,</strong></p>
                            <p className="italic text-gray-600">Generated by Nyaya-Sahayak AI</p>
                            <p className="text-xs text-gray-500 mt-1">Legal First Responder System</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ResultsPanel;
